/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PropertyDetails {
  'status' : PropertyStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'sellerContact' : { 'name' : string, 'email' : string, 'phone' : string },
  'description' : string,
  'amenities' : Array<string>,
  'listingDate' : Time,
  'updatedAt' : Time,
  'squareFootage' : bigint,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : { 'area' : string, 'city' : string },
  'images' : Array<ExternalBlob>,
}
export type PropertyId = bigint;
export interface PropertySearchCriteria {
  'status' : [] | [PropertyStatus],
  'propertyType' : [] | [PropertyType],
  'area' : [] | [string],
  'city' : [] | [string],
  'minBedrooms' : [] | [bigint],
  'maxPrice' : [] | [bigint],
  'minPrice' : [] | [bigint],
  'minBathrooms' : [] | [bigint],
}
export type PropertyStatus = { 'pending' : null } |
  { 'sold' : null } |
  { 'available' : null };
export type PropertyType = { 'house' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProperty' : ActorMethod<[PropertyDetails], PropertyId>,
  'deleteProperty' : ActorMethod<[PropertyId], undefined>,
  'getAllProperties' : ActorMethod<[], Array<PropertyDetails>>,
  'getAvailableProperties' : ActorMethod<[], Array<PropertyDetails>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPropertiesByOwner' : ActorMethod<[Principal], Array<PropertyDetails>>,
  'getProperty' : ActorMethod<[PropertyId], PropertyDetails>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProperties' : ActorMethod<
    [[] | [PropertySearchCriteria]],
    Array<PropertyDetails>
  >,
  'updateProperty' : ActorMethod<[PropertyId, PropertyDetails], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];