/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sold' : IDL.Null,
  'available' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'house' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PropertyDetails = IDL.Record({
  'status' : PropertyStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'sellerContact' : IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  }),
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'listingDate' : Time,
  'updatedAt' : Time,
  'squareFootage' : IDL.Nat,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Record({ 'area' : IDL.Text, 'city' : IDL.Text }),
  'images' : IDL.Vec(ExternalBlob),
});
export const PropertyId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PropertySearchCriteria = IDL.Record({
  'status' : IDL.Opt(PropertyStatus),
  'propertyType' : IDL.Opt(PropertyType),
  'area' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'minBedrooms' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
  'minBathrooms' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProperty' : IDL.Func([PropertyDetails], [PropertyId], []),
  'deleteProperty' : IDL.Func([PropertyId], [], []),
  'getAllProperties' : IDL.Func([], [IDL.Vec(PropertyDetails)], ['query']),
  'getAvailableProperties' : IDL.Func(
      [],
      [IDL.Vec(PropertyDetails)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPropertiesByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PropertyDetails)],
      ['query'],
    ),
  'getProperty' : IDL.Func([PropertyId], [PropertyDetails], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProperties' : IDL.Func(
      [IDL.Opt(PropertySearchCriteria)],
      [IDL.Vec(PropertyDetails)],
      ['query'],
    ),
  'updateProperty' : IDL.Func([PropertyId, PropertyDetails], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sold' : IDL.Null,
    'available' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'house' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PropertyDetails = IDL.Record({
    'status' : PropertyStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'sellerContact' : IDL.Record({
      'name' : IDL.Text,
      'email' : IDL.Text,
      'phone' : IDL.Text,
    }),
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'listingDate' : Time,
    'updatedAt' : Time,
    'squareFootage' : IDL.Nat,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Record({ 'area' : IDL.Text, 'city' : IDL.Text }),
    'images' : IDL.Vec(ExternalBlob),
  });
  const PropertyId = IDL.Nat;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PropertySearchCriteria = IDL.Record({
    'status' : IDL.Opt(PropertyStatus),
    'propertyType' : IDL.Opt(PropertyType),
    'area' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'minBedrooms' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
    'minBathrooms' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProperty' : IDL.Func([PropertyDetails], [PropertyId], []),
    'deleteProperty' : IDL.Func([PropertyId], [], []),
    'getAllProperties' : IDL.Func([], [IDL.Vec(PropertyDetails)], ['query']),
    'getAvailableProperties' : IDL.Func(
        [],
        [IDL.Vec(PropertyDetails)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPropertiesByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PropertyDetails)],
        ['query'],
      ),
    'getProperty' : IDL.Func([PropertyId], [PropertyDetails], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProperties' : IDL.Func(
        [IDL.Opt(PropertySearchCriteria)],
        [IDL.Vec(PropertyDetails)],
        ['query'],
      ),
    'updateProperty' : IDL.Func([PropertyId, PropertyDetails], [], []),
  });
};

export const init = ({ IDL }) => { return []; };